### OpenCV 영상

##### 캠코더 영상 출력

In [1]:
import cv2

webcam = cv2.VideoCapture(0)
webcam.set(cv2.CAP_PROP_FRAME_WIDTH, 640)
webcam.set(cv2.CAP_PROP_FRAME_HEIGHT, 480)

if not webcam.isOpened():
    print("Could not open webcam")
    exit()

while webcam.isOpened():
    status, frame = webcam.read()

    if status:
        cv2.imshow("test", frame)

    if cv2.waitKey(1) & 0xFF == ord('q'): # 0또는 1의 경우 계속적으로 읽어옴
        break

webcam.release()
cv2.destroyAllWindows()


KeyboardInterrupt: 

##### 특정 시간 단위로 화면 저장

In [ ]:
import cv2

webcam = cv2.VideoCapture(0)
webcam.set(cv2.CAP_PROP_FRAME_WIDTH, 640)
webcam.set(cv2.CAP_PROP_FRAME_HEIGHT, 480)
cnt=0

if not webcam.isOpened():
    print("Could not open webcam")
    exit()

while webcam.isOpened():
    status, frame = webcam.read()
    if status:
        cv2.imshow("test", frame)
        fileName='frame' + str(cnt) + '.jpg'
        cv2.imwrite('d:/output/'+fileName, frame)
        cnt+=1
    if cv2.waitKey(3000) & 0xFF == ord('q'): # cv2.waitKey에 넣는 값에 따라 시간이 지정됨, 3000 : 3초
        break

webcam.release()
cv2.destroyAllWindows()

##### 특정 키를 누를 시 화면 저장

In [2]:
import cv2
webcam = cv2.VideoCapture(0)
webcam.set(cv2.CAP_PROP_FRAME_WIDTH, 640)
webcam.set(cv2.CAP_PROP_FRAME_HEIGHT, 480)
cnt=0
if not webcam.isOpened():
    print("Could not open webcam")
    exit()
while webcam.isOpened():
    status, frame = webcam.read()
    if status:
        cv2.imshow("test", frame)
 
    if cv2.waitKey(1)==ord('a'):
        fileName='frame' + str(cnt) + '.jpg'
        cv2.imwrite('d:/output/'+fileName, frame)
        print('a키가 눌려서 저장되었습니다.')
        cnt+=1

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

webcam.release()
cv2.destroyAllWindows()


KeyboardInterrupt: 

##### Video 일정 영역 채우기

In [3]:
import cv2

webcam = cv2.VideoCapture(0)
webcam.set(cv2.CAP_PROP_FRAME_WIDTH, 640)
webcam.set(cv2.CAP_PROP_FRAME_HEIGHT, 480)

if not webcam.isOpened():
    print("Could not open webcam")
    exit()

while webcam.isOpened():
    status, frame = webcam.read()
    if status:
        frame[100:300, 200:400]=0
        cv2.imshow("test", frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

webcam.release()
cv2.destroyAllWindows()

KeyboardInterrupt: 

##### Video 일정 영역을 사진으로 채우기

In [4]:
import cv2

dog=cv2.imread('c:/Users/user/Desktop/mtvs/week7/face/2face.jpg', cv2.IMREAD_COLOR)
dog=cv2.resize(dog, (400-200,300-100))
webcam = cv2.VideoCapture(0)
webcam.set(cv2.CAP_PROP_FRAME_WIDTH, 640)
webcam.set(cv2.CAP_PROP_FRAME_HEIGHT, 480)

if not webcam.isOpened():
    print("Could not open webcam")
    exit()

while webcam.isOpened():
    status, frame = webcam.read()
    if status:
        frame[100:300, 200:400]=dog
        cv2.imshow("test", frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

webcam.release()
cv2.destroyAllWindows()

KeyboardInterrupt: 

### video 파일에서 얼굴 영역 검출

In [1]:
from keras.models import load_model
model = load_model('keras_model.h5')  

#model.weights

import cv2
import numpy as np
class_name=['Female','Male']     
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')

webcam = cv2.VideoCapture(0)
webcam.set(cv2.CAP_PROP_FRAME_WIDTH, 640)
webcam.set(cv2.CAP_PROP_FRAME_HEIGHT, 480)

if not webcam.isOpened():
    print("Could not open webcam")
    exit()

while webcam.isOpened():
    status, frame = webcam.read()

    if status:
        cv2.imshow("test", frame)
        
        # 얼굴 찾기
        faces = face_cascade.detectMultiScale(frame, 1.3, 5)

        cnt=0
        for (x, y, w, h) in faces:
            cv2.rectangle(frame, (x-20, y-20), (x + w+20, y + h+20), (255, 0, 0), 2)
            사각영역array = frame[y-20:y + h+20, x-20:x + w+20]
            print(x,y,w,h)
            
            ### 모델에 넣기 위한 작업
            resize_img = cv2.resize(사각영역array, (224, 224))
            imgArr=(resize_img/127.0)-1   # 티처블 코드에 있었음
            prediction=imgArr.reshape(1,224,224,3) # 인공지능은  array 를 하나 확장한 tensor로 해야함. (224,224,3)을 1,224,224,3 으로 확장함
            result=model.predict(prediction)
            argmaxNumber=np.argmax(result)   # 출력결과가 0이면 0번째 위치값이 predict 출력값중에 0번째 위치값이 가장 크다는 뜻
            printTxt=class_name[argmaxNumber]
            cv2.putText(frame, printTxt , (x-10,y-30), cv2.FONT_HERSHEY_SIMPLEX, 1, (255,0,0), 2)
            cv2.imshow("test", frame)



    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

webcam.release()
cv2.destroyAllWindows()

202 157 69 69
176 64 206 206
173 59 213 213
167 55 221 221
165 50 226 226
164 47 230 230
171 63 213 213
173 60 213 213
162 48 230 230
167 55 221 221
171 55 216 216
165 50 226 226
164 47 230 230
168 53 222 222
170 57 218 218
164 52 226 226
163 50 226 226
176 59 201 201
174 58 206 206
163 48 230 230
166 51 226 226
168 53 222 222
168 54 220 220
168 52 222 222
173 60 211 211
169 59 213 213
169 59 213 213
183 62 191 191
175 50 216 216
177 61 203 203
180 58 204 204
191 52 211 211
187 51 221 221
193 44 230 230
192 38 235 235
191 37 238 238
204 45 230 230
199 44 235 235
196 34 247 247
204 43 235 235
199 36 245 245
211 41 216 216
212 29 227 227
212 29 227 227
208 26 233 233
214 28 226 226
233 81 188 188
227 72 196 196
230 78 190 190
224 101 196 196
226 104 188 188
237 112 176 176
237 121 174 174
250 129 152 152
244 120 166 166
250 127 157 157
251 133 156 156
251 123 161 161
246 115 181 181
251 116 174 174
242 103 196 196
245 94 196 196
246 90 196 196
243 87 196 196
208 58 233 233
198 57 240 240

KeyboardInterrupt: 

In [2]:
import cv2

webcam = cv2.VideoCapture(0)
webcam.set(cv2.CAP_PROP_FRAME_WIDTH, 640)
webcam.set(cv2.CAP_PROP_FRAME_HEIGHT, 480)

face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')qqqq

if not webcam.isOpened():
    print("Could not open webcam")
    exit()

while webcam.isOpened():
    status, frame = webcam.read()
    if status:
        face = face_cascade.detectMultiScale(frame, scaleFactor=1.1, minNeighbors=5, minSize=(20,20)) 
        print(face)
        cv2.imshow("test", frame)
        
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

webcam.release()
cv2.destroyAllWindows()

()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
[[413 314  42  42]]
()
()
()
[[412 312  46  46]]
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
[[414 315  40  40]]
()
()
()
[[414 315  40  40]]
()
()
[[414 315  40  40]]
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()


KeyboardInterrupt: 

: 