In [3]:
def prnLine(x1='-',x2=100):
    print(x1*x2)

prnLine()
prnLine("#")
prnLine(x2=5)
prnLine("#",5)
prnLine(x2=5,x1="#")


def title():
    prnLine()
    txt='''
        date:2023-6-1
        writer : ej
        version : 1.2
        lan : python
    '''
    print(txt)
    prnLine()

title()


----------------------------------------------------------------------------------------------------
####################################################################################################
-----
#####
#####
----------------------------------------------------------------------------------------------------

        date:2023-6-1
        writer : ej
        version : 1.2
        lan : python
    
----------------------------------------------------------------------------------------------------


In [5]:
def a(*args):
    tmp=0
    for i in args:
        tmp+=i
    return tmp

b=a() # * -> 데이터를 스칼라값으로 넣는데 얼마나 넣을지 모를 때 사용
b

0

In [ ]:
def a(x):
    tmp=0
    for i in x:
        tmp=tmp+i
    return tmp

b=a([3,4,56,7])
b

In [7]:
a = {'phone':['010-9999-1234','111','222'],
     'birth':['1111','22','333']}

print(a.keys())
a['phone']

dict_keys(['phone', 'birth'])


['010-9999-1234', '111', '222']

In [21]:
a = {'info':{'le':'python',
             'wr':'ej',
             'ver':'1.0'
            },   
     'data':{  
            'phone':['010-9999-1234','111','222'],
            'birth':['1111','22','333'],
            'eye':{'eyeL':[1.0,2.0,1.5],
                   'eyeR':[1.5,2.0,1.0]}
            }
}
# 위의 형식을 저장하면 json
# json으로 저장하면 key value 나눠서 저장됨
# json으로 저장 시 읽어낼 때 info, data key로 저장

a.keys()
a['data'].keys()
a['data']['phone']
a['info']['le']
a['data']['eye']['eyeL'][0]


1.0

In [26]:
x=dict({'kor':[9,5,3], 'eng':[2,3,4], 'mat':[3,7,3]})  # 크롤링 시 자주 사용
pd.DataFrame(x)

# for 크롤링:
#     korlist.append(3)
# x=dict({'kor':korlist, 'eng':[2,3,4], 'mat':[3,7,3]})  # 크롤링 시 자주 사용
# pd.DataFrame(x)

kor  eng  mat
0    9    2    3
1    5    3    7
2    3    4    3

In [25]:
import numpy as np
import pandas as pd

a=np.random.rand(5,3)*7
a=a.astype('int32')

df=pd.DataFrame(a, columns=['kor','eng','mat'])
df

kor  eng  mat
0    0    3    1
1    2    4    5
2    4    5    0
3    4    1    3
4    5    5    6

In [35]:
import numpy as np
w=np.random.rand(3)*7
w=w.astype('int32')
print(w)
w*df
# weight (가중치) 값을 만드는 과정

[2 6 4]


kor  eng  mat
0    0   18    4
1    4   24   20
2    8   30    0
3    8    6   12
4   10   30   24

In [38]:
print(df.values)
print(df.values * w)   # array가 됨

# 예측값은 행단위로 더한 값임
np.dot(df.values, w)
# y와 해당 예측값(최종값)이 얼마나 차이 날것인가
# 가장 적은 오차를 갖는 weight를 찾는 방법

[[0 3 1]
 [2 4 5]
 [4 5 0]
 [4 1 3]
 [5 5 6]]
[[ 0 18  4]
 [ 4 24 20]
 [ 8 30  0]
 [ 8  6 12]
 [10 30 24]]


array([22, 48, 38, 26, 64])

In [45]:
len(df.values[0])  # weight로 필요한 수 확인

3

함수화 시키기

In [43]:
def w(x):        
    import numpy as np
    colCnt=len(x[0])
    w=np.random.rand(colCnt)*7
    w=w.astype('int32')
    return w

def cal(data, w):
    return np.dot(data, w)  # 내적곱


we=w(df.values)
cal(df.values, we)  # y 예측값 계산


array([14, 43, 27, 30, 60])

In [46]:
class prn:
    def __init__(self,x):
        print(x+'태어남')
    def prnLine():
        print('-'*10)
    def prnTile():
        print('wwwpython')

prn('000')

000태어남
