#### 파이썬 변수 타입

In [5]:
#예약어는 변수로 사용 불가
print="3" # print라는 예약어는 사라짐

del print # 변수를 메모리에서 제거, 쓸데없는 변수는 지우는 것이 좋음
print('a')

a


In [4]:
print(5)

TypeError: 'str' object is not callable

In [ ]:
# 변수에 값 할당, 변수 선언은 다른 개념
# 변수 선언은 프로그램에 따라 필수여부 다름 -> python은 필요x -> 메모리 낭비가 심함(각 변수의 메모리 크기를 정해주지 않기때문)
# 변수 선언은 dtype 선언

a=3
a='bb'  # 메모리 번지를 a라고 명명 그 번지에 값을 넣음
print(a)  # a가 명명된 메모리의 내용을 디스플레이함
a=['a','b','c']  # 0번 위치에는 'a'가 들어간 장소의 번지와 1번위치의 주소번지를 기억함
a=np.array(['a','b','c']) # 행열을 기억하는 장소의 번지를 기억함

In [7]:
def mytype(*args):
    for i in args:
        print(i,'---',type(i))

mytype(1,1.,'a','aa',[1,2])

1 --- <class 'int'>
1.0 --- <class 'float'>
a --- <class 'str'>
aa --- <class 'str'>
[1, 2] --- <class 'list'>


In [9]:
1+1.  # 정수 실수 연산은 실수
a=1
type(a)

int

In [10]:
import numpy as np

a=np.array([1,2,3])
a*1.  # 소수 이하 연산의 경우astype을 안 하고 바로 연산 가능

# 변수 타입에 따라 변수를 바꾸는 방법론이 다름
# list의 type 변형 시 각 요소를 읽어올 때 -> for문으로 하나씩 바꾸거나, map함수 이용

array([1., 2., 3.])

In [19]:
# 파이썬 자료형 
# 스칼라, 벡터, array, 튜플, 딕셔너리

A=[1,1,2,1,1,2,1]
set(A)  # 중복제거 -> UNIQUE한 값을 찾음
# set함수는 인덱싱을 갖지 않음! -> 인덱싱이 필요한 경우 set을 쓰면 안 됨

b=set(A)
list(b)[0]  # list로 감싸는 경우 인덱싱 가능

1

In [14]:
list_str=['1','2','3']

for i in range(len(list_str)):  # 인덱싱 호출하는 경우 속도가 느리므로 사용하지 않는 것이 좋음
    list_str[i]=int(list_str[i])

list_str

[1, 2, 3]

In [21]:
np.unique(A)  # set과 unique 함수 기억!  -> unique : 인덱싱 및 카운트, return 값 등을 가짐

array([1, 2])

In [13]:
# 변수 타입에 따라 변수를 바꾸는 방법론이 다름
# list의 type 변형 시 각 요소를 읽어올 때 -> for문으로 하나씩 바꾸거나, map함수 이용

list_str=['1','2','3']
list_int = list(map(int, list_str))  #정수로 변환, tuple을 list로 변환한 것과 같은 의미
list_str2 = list(map(str, list_int))  #문자열로 변환
print(list_int)
print(list_str2)

[1, 2, 3]
['1', '2', '3']


In [27]:
txt = 'abcdefg'

for i in txt:
    print(i)
    #문자열 슬라이싱

txt[:3]

strsplit=3
a=''
cnt=0
# 슬라이싱 없이 for문으로 구현
for i in txt:
    if cnt>=strsplit:
        break
    a+=i
    cnt+=1

a

a
b
c
d
e
f
g


'abc'

### 크롤링에 사용

In [34]:
# blog1='파이썬 공부 일정'
# blog2='강아지와 늘 산책 잠'

txt='파이썬 공부 일정 \n 강아지와 늘 산책 잠'  # \n을 어떤 단위로 list str을 나눌지 고민해야함 -> 크롤링 시 중요 (연관도 분석을 위해)
txt.split('\n')
# 가져올 때 리스트 안에서 나눌 수 있는 구분자를 잘 생각해야함 -> 크롤링 시 주의

txt.split(' ')
data=np.unique(txt, return_counts=True)

# join 함수 : 문자열과 문자열의 연결, for를 안 쓰고 가능

(array(['파이썬 공부 일정 \n 강아지와 늘 산책 잠'], dtype='<U23'), array([1], dtype=int64))

In [44]:
##워드 클라우드는 리스트로 나누어진 문장을 한개의 문자열로 모아서 (여러개의 리스트라면 한개로 모아야함)
# 단어셋을 제작하고(구분자로 나누던지, 명사형을 취하던지), 단어셋의 빈도수로 문장의 중요 단어를 체크
txt=['파이썬 공부 일정',
    '강아지와 늘 산책 공부 잠']

result=''
for i in txt:
    result+=i
result

wordlist=result.split(' ')

In [47]:
def mycount(*qword):
    for i in qword:
        print(wordlist.count(i))


word1='파이썬'
word2='공부'
#qword=['파이썬','공부']
result=mycount(word1, word2)
result

1
2


In [48]:
def mycount(*qword):  # 외부데이터를 받아서 return 하는 경우 argument로 받는 것이 좋음
    tmp=[]
    for i in qword:
        tmp.append(wordlist.count(i))
        #print(wordlist.count(i))
    return tmp

word1='파이썬'
word2='공부'
#qword=['파이썬','공부']
result=mycount(word1, word2)
result

[1, 2]

In [40]:
data=np.unique(wordlist, return_counts=True)
data

(array(['공부', '늘', '산책', '일정강아지와', '잠', '파이썬'], dtype='<U6'),
 array([2, 1, 1, 1, 1, 1], dtype=int64))