In [1]:
import cv2
import numpy as np
import torch
from torchvision import transforms

model = torch.load('drowsiness_detect.pt')
model.load_state_dict(torch.load('drowsiness_detect_state_dict.pt')) 

model.eval()

class_name=['Closed_eyes', 'Open_eyes']     
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_eye.xml')

webcam = cv2.VideoCapture(0)
webcam.set(cv2.CAP_PROP_FRAME_WIDTH, 640)
webcam.set(cv2.CAP_PROP_FRAME_HEIGHT, 480)

if not webcam.isOpened():
    print("Could not open webcam")
    exit()

while webcam.isOpened():
    status, frame = webcam.read()

    if status:
        height,width = frame.shape[0:2]
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        
        # 얼굴, 눈 찾기
        faces = face_cascade.detectMultiScale(gray, 1.2, 3)
        eyes = eye_cascade.detectMultiScale(gray, scaleFactor= 1.1, minNeighbors=1)

        cv2.rectangle(frame, (0,height-50),(200,height),(0,0,0),thickness=cv2.FILLED)

        for (x,y,w,h) in faces:
            cv2.rectangle(frame,pt1=(x,y),pt2=(x+w,y+h), color= (255,0,0), thickness=3)

        transform = transforms.Compose([transforms.Resize((64, 64)),
                                        transforms.ToTensor()])

        for (ex,ey,ew,eh) in eyes:
            eye =frame[ey:ey+eh,ex:ex+w]
            eye= cv2.resize(eye,(240,240))
            # print(eye)
            cv2.imshow('eyes', eye)
            # eye= eye/255
            # eye= eye.reshape(64,64,3)
            # eye= np.expand_dims(eye,axis=0)
            # print(eye)

            # with torch.no_grad():
            #     prediction = model(torch.tensor(eye, dtype=torch.float32))
            #     print(prediction)


webcam.release()
cv2.destroyAllWindows()

## 얼굴 및 눈 영역 검출

In [2]:
import cv2
import numpy as np
import torch
from torchvision import transforms

model = torch.load('drowsiness_detect.pt')
model.load_state_dict(torch.load('drowsiness_detect_state_dict.pt')) 

model.eval()

class_name=['Closed_eyes', 'Open_eyes']     
face_cascade = cv2.CascadeClassifier('d:/haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier('d:/haarcascade_eye.xml')

# webcam = cv2.VideoCapture(0)
webcam = cv2.VideoCapture('d:/drowsiness_video_data/SGA2100300S0042.mp4')
# webcam.set(cv2.CAP_PROP_FRAME_WIDTH, 640)
# webcam.set(cv2.CAP_PROP_FRAME_HEIGHT, 480)

font = cv2.FONT_ITALIC

if not webcam.isOpened():
    print("Could not open webcam")
    exit()

while webcam.isOpened():
    status, frame = webcam.read()

    if status:
        height,width = frame.shape[0:2]
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        
        # 얼굴, 눈 찾기
        faces = face_cascade.detectMultiScale(gray, 1.3, 5)
        # eyes = eye_cascade.detectMultiScale(gray, scaleFactor= 1.3, minNeighbors=1)

        # cv2.rectangle(frame, (0,height-50),(200,height),(0,0,0),thickness=cv2.FILLED)

        for (x,y,w,h) in faces:
            cv2.rectangle(frame,pt1=(x,y),pt2=(x+w,y+h), color= (255,0,0), thickness=2)
            cv2.putText(frame, 'Detected Face', (x-5, y-5), font, 0.5, (255,255,0),2)

            roi_eye_gray = gray[y:y+h, x:x+w]
            roi_eye_color = frame[y:y+h, x:x+w]
            eyes = eye_cascade.detectMultiScale(roi_eye_gray)

            for (ex,ey,ew,eh) in eyes:
                cv2.rectangle(roi_eye_color,pt1=(ex,ey),pt2=(ex+ew,ey+eh), color= (255,0,0), thickness=2)
                # eye =frame[ey:ey+eh,ex:ex+w]
                # eye= cv2.resize(eye,(64,64))

                # cv2.imshow('test', frame)
            # print(eye)
            # eye_input = eye.copy().reshape((1, IMG_SIZE[1], IMG_SIZE[0], 1)).astype(np.float32)


        cv2.imshow("test", frame)
        # cv2.imshow('eyes', eye)

    if cv2.waitKey(1) & 0xFF == ord('q'): # 0또는 1의 경우 계속적으로 읽어옴
        break

webcam.release()
cv2.destroyAllWindows()

KeyboardInterrupt: 

In [8]:
import cv2
import numpy as np
import torch

model = torch.load('drowsiness_detect.pt')
model.load_state_dict(torch.load('drowsiness_detect_state_dict.pt')) 

model.eval()

class_name=['Closed_eyes', 'Open_eyes']     
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_eye.xml')

webcam = cv2.VideoCapture(0)
webcam.set(cv2.CAP_PROP_FRAME_WIDTH, 640)
webcam.set(cv2.CAP_PROP_FRAME_HEIGHT, 480)

if not webcam.isOpened():
    print("Could not open webcam")
    exit()

while webcam.isOpened():
    status, frame = webcam.read()

    if status:
        height,width = frame.shape[0:2]
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        
        # 얼굴, 눈 찾기
        faces = face_cascade.detectMultiScale(gray, 1.2, 3)
        eyes= eye_cascade.detectMultiScale(gray, scaleFactor= 1.1, minNeighbors=1)

        cv2.rectangle(frame, (0,height-50),(200,height),(0,0,0),thickness=cv2.FILLED)

        for (x,y,w,h) in faces:
            cv2.rectangle(frame,pt1=(x,y),pt2=(x+w,y+h), color= (255,0,0), thickness=3)

        for (ex,ey,ew,eh) in eyes:

            eye= frame[ey:ey+eh,ex:ex+w]
            eye= cv2.resize(eye,(64,64))
            eye= eye/255
            eye= eye.reshape(64,64,3)
            eye= np.expand_dims(eye,axis=0)
            print(eye)

            # with torch.no_grad():
            #     prediction = model(torch.tensor(eye, dtype=torch.float32))
            #     print(prediction)

[[[[0.14117647 0.17647059 0.23137255]
   [0.34509804 0.40784314 0.49803922]
   [0.39215686 0.45490196 0.56470588]
   ...
   [0.28235294 0.28235294 0.29019608]
   [0.29019608 0.29019608 0.29803922]
   [0.3372549  0.3372549  0.3372549 ]]

  [[0.15294118 0.18823529 0.23921569]
   [0.34509804 0.40784314 0.49803922]
   [0.39215686 0.45882353 0.56470588]
   ...
   [0.27843137 0.28235294 0.29019608]
   [0.29019608 0.28627451 0.29411765]
   [0.33333333 0.33333333 0.33333333]]

  [[0.18431373 0.22352941 0.27843137]
   [0.34117647 0.41176471 0.49803922]
   [0.39607843 0.46666667 0.56862745]
   ...
   [0.27843137 0.28235294 0.28627451]
   [0.2745098  0.2745098  0.28235294]
   [0.32156863 0.3254902  0.3254902 ]]

  ...

  [[0.48627451 0.58039216 0.6745098 ]
   [0.46666667 0.56862745 0.6745098 ]
   [0.45098039 0.56470588 0.6745098 ]
   ...
   [0.14117647 0.14509804 0.14901961]
   [0.14117647 0.14509804 0.14901961]
   [0.14117647 0.14901961 0.15294118]]

  [[0.49019608 0.58039216 0.6745098 ]
   [0.4

KeyboardInterrupt: 

In [1]:
import cv2
import numpy as np
import torch

model = torch.load('drowsiness_detect.pt')
model.load_state_dict(torch.load('drowsiness_detect_state_dict.pt')) 

model.eval()

class_name=['Closed_eyes', 'Open_eyes']     
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_eye.xml')

webcam = cv2.VideoCapture(0)
webcam.set(cv2.CAP_PROP_FRAME_WIDTH, 640)
webcam.set(cv2.CAP_PROP_FRAME_HEIGHT, 480)

if not webcam.isOpened():
    print("Could not open webcam")
    exit()

while webcam.isOpened():
    status, frame = webcam.read()

    if status:
        height,width = frame.shape[0:2]
        
        # 얼굴, 눈 찾기
        faces = face_cascade.detectMultiScale(frame, 1.2, 3)
        eyes= eye_cascade.detectMultiScale(gray, scaleFactor= 1.1, minNeighbors=1)

        cnt=0
        for (x, y, w, h) in faces:
            cv2.rectangle(frame, (x-20, y-20), (x + w+20, y + h+20), (255, 0, 0), 2)
            사각영역array = frame[y-20:y + h+20, x-20:x + w+20]
            print(x,y,w,h)
            
            ### 모델에 넣기 위한 작업
            resize_img = cv2.resize(사각영역array, (64, 64))
            imgArr=(resize_img/127.0)-1  
            prediction=imgArr.reshape(1,64,64,3) 
            result=resnet50(prediction)

            argmaxNumber=np.argmax(result)   # 출력결과가 0이면 0번째 위치값이 predict 출력값중에 0번째 위치값이 가장 크다는 뜻
            printTxt=class_name[argmaxNumber]
            cv2.putText(frame, printTxt , (x-10,y-30), cv2.FONT_HERSHEY_SIMPLEX, 1, (255,0,0), 2)
            cv2.imshow("test", frame)

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

webcam.release()
cv2.destroyAllWindows()

61 174 176 176


TypeError: conv2d() received an invalid combination of arguments - got (numpy.ndarray, Parameter, NoneType, tuple, tuple, tuple, int), but expected one of:
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, tuple of ints padding, tuple of ints dilation, int groups)
      didn't match because some of the arguments have invalid types: (!numpy.ndarray!, !Parameter!, !NoneType!, !tuple of (int, int)!, !tuple of (int, int)!, !tuple of (int, int)!, int)
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, str padding, tuple of ints dilation, int groups)
      didn't match because some of the arguments have invalid types: (!numpy.ndarray!, !Parameter!, !NoneType!, !tuple of (int, int)!, !tuple of (int, int)!, !tuple of (int, int)!, int)
