### GridSearchCV

In [1]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Lasso
from sklearn.model_selection import GridSearchCV
import pandas as pd

In [2]:
x_data = np.array([
    [2, 1],
    [3, 2],
    [3, 4],
    [5, 5],
    [7, 5],
    [2, 5],
    [8, 9],
    [9, 10],
    [6, 12],
    [9, 2],
    [6, 10],
    [2, 4]
])
y_data = np.array([3, 5, 7, 10 ,12, 7, 13, 13, 12, 13, 12, 6])


In [4]:
x_train, x_test, y_train, y_test = train_test_split(x_data,
                                                    y_data,
                                                    test_size=0.3,
                                                    random_state=777)

In [5]:
x_train, x_test, y_train, y_test

(array([[ 6, 12],
        [ 7,  5],
        [ 2,  5],
        [ 9,  2],
        [ 3,  2],
        [ 2,  4],
        [ 8,  9],
        [ 9, 10]]),
 array([[ 6, 10],
        [ 2,  1],
        [ 5,  5],
        [ 3,  4]]),
 array([12, 12,  7, 13,  5,  6, 13, 13]),
 array([12,  3, 10,  7]))

In [6]:
model = Lasso()
param_grid = {'alpha':[0.01,0.1,1,10,100]}
grid = GridSearchCV(model, param_grid=param_grid) 

In [7]:
grid.fit(x_train, y_train)
print(grid.best_params_)
df = pd.DataFrame(grid.cv_results_)
print(df.sort_values(by=['param_alpha'])[['params','mean_test_score']])

{'alpha': 0.01}
            params  mean_test_score
0  {'alpha': 0.01}              NaN
1   {'alpha': 0.1}              NaN
2     {'alpha': 1}              NaN
3    {'alpha': 10}              NaN
4   {'alpha': 100}              NaN


c:\Users\user\miniconda3\envs\py\Lib\site-packages\sklearn\metrics\_regression.py:918: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\user\miniconda3\envs\py\Lib\site-packages\sklearn\metrics\_regression.py:918: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\user\miniconda3\envs\py\Lib\site-packages\sklearn\metrics\_regression.py:918: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\user\miniconda3\envs\py\Lib\site-packages\sklearn\metrics\_regression.py:918: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\user\miniconda3\envs\py\Lib\site-packages\sklearn\metrics\_regression.py:918: UndefinedMetricWarning: R^2 score is not well-defined wit

In [9]:
best_model = grid.best_estimator_
y_predict = best_model.predict(x_test)

print(y_predict[2])

9.144338874784689


In [ ]:
print(grid.score(x_test, y_test))

In [ ]:
print(grid.predict([[2,1]])[0])