### Basic Torch

In [2]:
import torch

import tensorflow as tf

In [8]:
vartf=tf.Variable([100,200,300])  # tensorflow의 변수 선언
type(vartf)
# vartf[0]=1
# vartf
vartf[0].assign(1)
vartf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([  1, 200, 300])>

In [5]:
varto=torch.tensor([100,200,300])
type(varto)
varto[0]=1
varto

tensor([  1, 200, 300])

In [10]:
a=tf.Variable([100,200,300])
b=tf.constant([1,2,3])
a,b

aa=[1,2,3]
b=tf.constant(aa)
b, tf.convert_to_tensor(aa)
# 모델에 데이터를 넣으면 다음과 같은 과정으로 들어감

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>)